[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install && cd client && npm install && cd .."]

[phases.build]
cmds = ["cd client && npm run build && cd .."]

[start]
cmd = "node server.js"
